version: '3.7'
services:
    nginx:
        image: nginx:1.21.6-alpine
        container_name: nginx
        working_dir: /var/www/html
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/development/nginx/ssl/:/etc/nginx/ssl/
            - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
            - app
        depends_on:
            - app
        ports:
            - '443:443'
        networks:
            - collection-agency

    app:
        container_name: php
        build:
            args:
                user: ${APP_NAME}
                uid: 1000
            context: ./docker/development/php
            dockerfile: php.docker
        environment:
            APP_NAME: ${APP_NAME}
        volumes:
            - ./docker/development/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - collection-agency
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    collection-agency_data:

networks:
    collection-agency:
        driver: bridge
